# -*- coding: utf-8 -*-
"""
Master term list for "تطبيق المرشد" — Syrian 3rd-secondary scientific-branch
Physics, grounded in the official textbook.

SOURCE OF EVERY ROW
  tier "k"  = الكلمات المفتاحية printed at the head of the chapter (official)
  tier "g"  = جدول «المصطلحات الانكليزية» at the end of the book (official, bilingual)
  tier "s"  = symbols / constants / units  (proposed from the book's equations)
  tier "v"  = general & laboratory vocabulary occurring in the book

COLUMNS: (arabic, english, symbol, unit, chapter_key, tier)
  symbol / unit may be "" when unknown -> the reviewer fills them in.
"""

CHAPTERS = [
    ("U1",   "الوحدة الأولى: الحركة والتحريك"),
    ("U1C1", "الفصل 1: الحركة التوافقية البسيطة (ص6)"),
    ("U1C2", "الفصل 2: الاهتزازات الجيبية الدورانية – نوّاس الفتل غير المتخامد (ص20)"),
    ("U1C3", "الفصل 3: الاهتزازات غير التوافقية – النوّاس الثقلي غير المتخامد (ص28)"),
    ("U1C4", "الفصل 4: ميكانيك الموائع (ص42)"),
    ("U1C5", "الفصل 5: النسبية الخاصة (ص54)"),
    ("U2",   "الوحدة الثانية: الكهرباء والمغناطيسية"),
    ("U2C1", "الفصل 1: المغناطيسية (ص68)"),
    ("U2C2", "الفصل 2: فعل الحقل المغناطيسي في التيار الكهربائي (ص88)"),
    ("U2C3", "الفصل 3: التحريض الكهرطيسي (ص104)"),
    ("U2C4", "الفصل 4: الدارات المهتزة والتيارات عالية التواتر (ص126)"),
    ("U2C5", "الفصل 5: التيار المتناوب الجيبي (ص138)"),
    ("U2C6", "الفصل 6: المولدات الكهربائية (ص160)"),
    ("U3",   "الوحدة الثالثة: الأمواج المستقرة"),
    ("U3C1", "الفصل 1: الأمواج المستقرة العرضية (ص168)"),
    ("U3C2", "الفصل 2: الأمواج المستقرة الطولية (ص182)"),
    ("U4",   "الوحدة الرابعة: الإلكترونيات والجسم الصلب"),
    ("U4C1", "الفصل 1: النماذج الذرية والطيوف (ص198)"),
    ("U4C2", "الفصل 2: انتزاع الإلكترونات وتسريعها (ص210)"),
    ("U4C3", "الفصل 3: الأشعة المهبطية (ص218)"),
    ("U4C4", "الفصل 4: الفعل الكهرحراري (ص224)"),
    ("U4C5", "الفصل 5: نظرية الكم والفعل الكهرضوئي (ص230)"),
    ("U4C6", "الفصل 6: الأشعة السينية (ص240)"),
    ("U4C7", "الفصل 7: أشعة الليزر (ص246)"),
    ("U5",   "الوحدة الخامسة: الفيزياء الفلكية"),
    ("U5C1", "الفصل 1: الفيزياء الفلكية (ص254)"),
    ("SYM",  "القسم 0: الرموز والثوابت والوحدات"),
    ("GEN",  "القسم 6: مصطلحات عامة وعملية شائعة في الكتاب"),
    ("SYN",  "القسم 7-أ: مرادفات مسموحة في الشرح — ولا تُستعمل في الأسئلة"),
    ("BAN",  "القسم 7-ب: مصطلحات ممنوعة"),
]

# (arabic, english, symbol, unit, chapter_key, tier)
TERMS = [
    # ---------------- Unit 1 - Chapter 1 ----------------
    ("الحركة التوافقية البسيطة", "Simple Harmonic Motion", "", "", "U1C1", "k"),
    ("نابض", "Spring", "", "", "U1C1", "k"),
    ("قوة الإرجاع", "Restoring Force", "F", "N", "U1C1", "k"),
    ("المطال", "Amplitude", "x", "m", "U1C1", "k"),
    ("السعة", "Amplitude / Range", "X_max", "m", "U1C1", "k"),
    ("الدور", "Period", "T", "s", "U1C1", "k"),
    ("التواتر", "Frequency", "f", "Hz", "U1C1", "k"),
    ("الطاقة الكامنة المرونية", "Elastic Potential Energy", "Ep", "J", "U1C1", "k"),
    ("الطاقة الحركية", "Kinetic Energy", "E_K", "J", "U1C1", "k"),
    ("الطاقة الميكانيكية", "Mechanical Energy", "E", "J", "U1C1", "k"),
    ("الحركة الدائرية المنتظمة", "Uniform Circular Motion", "", "", "U1C1", "v"),
    ("مركز الاهتزاز", "Centre of Oscillation", "O", "", "U1C1", "v"),
    ("توابع الحركة", "Functions of the Motion", "", "", "U1C1", "v"),
    ("الطور", "Phase", "(ω₀t+φ)", "rad", "U1C1", "v"),
    ("الطور الابتدائي", "Initial Phase", "φ", "rad", "U1C1", "v"),
    ("النبض الخاص", "Angular Frequency (Pulsation)", "ω", "rad/s", "U1C1", "v"),
    ("السرعة الزاوية", "Angular Velocity", "ω", "rad/s", "U1C1", "s"),
    ("التابع الزمني", "Time Function", "", "", "U1C1", "v"),
    ("الحركة الجيبية الانسحابية", "Sinusoidal (Simple Harmonic) Motion", "", "", "U1C1", "v"),
    ("تمثيل فرينل (كما ورد في ص13)", "Fresnel's Representation", "", "", "U1C1", "v"),
    ("الاستطالة", "Elongation", "x", "m", "U1C1", "v"),
    ("الاستطالة السكونية", "Static Elongation", "x₀", "m", "U1C1", "v"),
    ("ثابت صلابة النابض", "Spring Constant / Stiffness", "k", "N/m", "U1C1", "s"),
    ("قوة توتر النابض", "Spring Tension Force", "F_S", "N", "U1C1", "v"),
    ("قوة الثقل", "Weight", "w", "N", "U1C1", "s"),
    ("النواس المرن", "Elastic (Spring) Pendulum", "", "", "U1C1", "v"),
    ("المعادلة التفاضلية", "Differential Equation", "", "", "U1C1", "v"),
    ("حالة السكون", "State of Rest", "", "", "U1C1", "v"),
    ("حالة الحركة", "State of Motion", "", "", "U1C1", "v"),
    ("السرعة الخطية", "Linear Velocity", "v", "m/s", "U1C1", "s"),
    ("التسارع", "Acceleration", "a", "m/s²", "U1C1", "s"),
    ("المسقط", "Projection", "", "", "U1C1", "v"),
    ("المنحني البياني", "Graph / Curve", "", "", "U1C1", "v"),

    # ---------------- Unit 1 - Chapter 2 ----------------
    ("نواس الفتل", "Torsional Pendulum", "", "", "U1C2", "k"),
    ("سلك الفتل", "Torsion Spring / Wire", "", "", "U1C2", "k"),
    ("ثابت فتل السلك", "Torsion Spring Constant", "K", "N·m/rad", "U1C2", "k"),
    ("مزدوجة الفتل", "Torsion Couple — المزدوجة نفسها Γ_η (الكتاب ص22). ⚠ ملف الأستاذ يخزّن التابع كحرف n لاتيني (U+006E) لا η يوناني — والأرجح أنه أثر طباعة؛ نعتمد η لموافقة الكتاب وقوله", "Γ_η", "m·N", "U1C2", "k"),
    ("عزم مزدوجة الفتل", "Moment of the Torsion Couple — Γ_η/Δ = −K·θ (ص22). التابع الأول = نوع المزدوجة، و/Δ = المحور", "Γ_η/Δ", "m·N", "U1C2", "k"),
    ("مزدوجة الوزن", "Couple of the Weight (about axis Δ)", "Γ_w/Δ", "m·N", "U1C2", "v"),
    ("مزدوجة ردّ الفعل", "Reaction Couple (about axis Δ)", "Γ_R/Δ", "m·N", "U1C2", "v"),
    ("المطال الزاوي", "Angular Amplitude", "θ", "rad", "U1C2", "k"),
    ("السعة الزاوية", "Angular Amplitude", "θ_max", "rad", "U1C2", "k"),
    ("الاهتزازات الجيبية الدورانية", "Sinusoidal Torsional Vibrations", "", "", "U1C2", "g"),
    ("نواس الفتل غير المتخامد", "Undamped Torsional Pendulum", "", "", "U1C2", "g"),
    ("عزم القوة", "Moment of a Force (Torque)", "Γ", "m·N", "U1C2", "s"),
    ("عزم العطالة", "Moment of Inertia", "I_Δ", "kg·m²", "U1C2", "s"),
    ("الدور الخاص", "Natural Period", "T₀", "s", "U1C2", "v"),
    ("الحركة الدورانية", "Rotational Motion", "", "", "U1C2", "v"),
    ("نابض لولبي", "Spiral (Coil) Spring", "", "", "U1C2", "v"),

    # ---------------- Unit 1 - Chapter 3 ----------------
    ("النواس الثقلي المركب", "Compound Gravity Pendulum", "", "", "U1C3", "k"),
    ("النواس الثقلي البسيط", "Simple Gravity Pendulum", "", "", "U1C3", "k"),
    ("الاهتزازات غير التوافقية", "Anharmonic Oscillations", "", "", "U1C3", "g"),
    ("النواس الثقلي غير المتخامد", "Non-Damped Gravity Pendulum", "", "", "U1C3", "g"),
    ("مركز العطالة", "Centre of Inertia", "C", "", "U1C3", "s"),
    ("طول النواس البسيط المواقت", "Equivalent (Synchronised) Pendulum Length", "l", "m", "U1C3", "v"),
    ("النواس البسيط", "Simple Pendulum", "", "", "U1C3", "g"),
    ("السعات الزاوية الصغيرة", "Small Angular Amplitudes", "", "", "U1C3", "v"),

    # ---------------- Unit 1 - Chapter 4 ----------------
    ("ميكانيك الموائع", "Fluid Mechanics", "", "", "U1C4", "g"),
    ("المائع المثالي", "Ideal Fluid", "", "", "U1C4", "k"),
    ("السائل المثالي", "Ideal Liquid", "", "", "U1C4", "k"),
    ("خط الانسياب", "Flow Line (Streamline)", "", "", "U1C4", "k"),
    ("الجريان المنتظم", "Uniform Flow", "", "", "U1C4", "k"),
    ("الجريان غير المنتظم", "Non-Uniform Flow", "", "", "U1C4", "k"),
    ("معدل التدفق الكتلي", "Mass Flow Rate", "Q", "kg/s", "U1C4", "k"),
    ("معدل التدفق الحجمي", "Volumetric Flow Rate", "Q_v", "m³/s", "U1C4", "k"),
    ("معادلة الاستمرارية", "Continuity Equation", "", "", "U1C4", "k"),
    ("معادلة برنولي", "Bernoulli's Equation", "", "", "U1C4", "k"),
    ("نظرية تورشيللي", "Torricelli's Theorem", "", "", "U1C4", "k"),
    ("قوة الرفع", "Lift Force", "F", "N", "U1C4", "k"),
    ("الضغط", "Pressure", "P", "Pa", "U1C4", "s"),
    ("اللزوجة", "Viscosity", "η", "Pa·s", "U1C4", "v"),
    ("الكتلة الحجمية", "Volumic Mass (Density)", "ρ", "kg/m³", "U1C4", "s"),
    ("مساحة المقطع", "Cross-Sectional Area", "S", "m²", "U1C4", "s"),

    # ---------------- Unit 1 - Chapter 5 ----------------
    ("النسبية الخاصة", "Special Relativity", "", "", "U1C5", "g"),
    ("جملة المقارنة", "Frame of Reference", "", "", "U1C5", "k"),
    ("سرعة الضوء في الخلاء", "Speed of Light in Vacuum", "c", "m/s", "U1C5", "k"),
    ("تباطؤ الزمن", "Time Dilation", "", "", "U1C5", "k"),
    ("تقلص الأطوال", "Length Contraction", "", "", "U1C5", "k"),
    ("ميكانيك نسبي", "Relativistic Mechanics", "", "", "U1C5", "k"),
    ("طاقة سكونية", "Rest Energy", "E₀", "J", "U1C5", "k"),
    ("تمدد الزمن", "Time Dilation", "Δt", "s", "U1C5", "v"),
    ("جمل المقارنة العطالية", "Inertial Frame of Reference", "", "", "U1C5", "v"),
    ("الكتلة النسبية", "Relativistic Mass", "m", "kg", "U1C5", "v"),

    # ---------------- Unit 2 - Chapter 1 ----------------
    ("المغناطيسية", "Magnetism", "", "", "U2C1", "g"),
    ("مغناطيس نضوي", "Horseshoe Magnet", "", "", "U2C1", "k"),
    ("حقل مغناطيسي", "Magnetic Field", "B", "T", "U2C1", "k"),
    ("شدة الحقل المغناطيسي", "Magnetic Field Strength", "B", "T", "U2C1", "k"),
    ("نواة حديد", "Iron Core", "", "", "U2C1", "k"),
    ("عامل النفاذية المغناطيسي", "Magnetic Permeability", "μ", "H/m", "U2C1", "k"),
    ("الحقل المغناطيسي الأرضي", "Earth's Magnetic Field", "", "T", "U2C1", "k"),
    ("الأثر المغناطيسي للتيار الكهربائي", "Magnetic Effect of Electric Current", "", "", "U2C1", "k"),
    ("شدة شعاع السطح", "Surface Vector Magnitude", "S", "m²", "U2C1", "k"),
    ("التدفق المغناطيسي", "Magnetic Flux", "Φ", "Wb", "U2C1", "k"),
    ("قوة لورنز", "Lorentz Force", "F", "N", "U2C1", "g"),
    ("الناظم", "Normal (to a surface)", "n", "", "U2C1", "s"),
    ("القطب الشمالي", "North Pole", "", "", "U2C1", "v"),
    ("القطب الجنوبي", "South Pole", "", "", "U2C1", "v"),
    ("خطوط الحقل", "Field Lines", "", "", "U2C1", "v"),
    ("دارة كهربائية مستوية", "Plane Electric Circuit", "", "", "U2C1", "v"),
    ("تيار كهربائي", "Electric Current", "I", "A", "U2C1", "s"),

    # ---------------- Unit 2 - Chapter 2 ----------------
    ("نظرية مكسويل", "Maxwell's Theory", "", "", "U2C2", "k"),
    ("مقياس غلفاني", "Galvanometer", "", "", "U2C2", "k"),
    ("دولاب بارلو", "Barlow's Wheel", "", "", "U2C2", "k"),
    ("القوة الكهرطيسية", "Electromagnetic Force", "F", "N", "U2C2", "s"),
    ("المزدوجة الكهرطيسية", "Electromagnetic Couple — ⚠ لا رمز لها في الكتاب (ص88-112 خالية من Γ تماماً)", "", "m·N", "U2C2", "v"),
    ("عزم المزدوجة الكهرطيسية", "Moment of the Electromagnetic Couple — Γ_Δ مؤكَّد بنصّ ملخصات الأستاذ: Γ_Δ=N·I·S·B·sinα = M·B·sinα، وشعاعياً Γ_Δ = M ∧ B، الوحدة m·N. (الكتاب لا يرمز لها، وقرار الأستاذ نافذ)", "Γ_Δ", "m·N", "U2C2", "v"),
    ("تجربة السكتين الكهرطيسية", "Rails (Barlow setup)", "", "", "U2C2", "v"),
    ("عناصر شعاع القوة", "Elements of a Force Vector", "", "", "U2C2", "v"),
    ("الحامل", "Line of Action (of a vector)", "", "", "U2C2", "v"),
    ("الجهة", "Direction", "", "", "U2C2", "v"),
    ("الشدة", "Magnitude / Intensity", "", "", "U2C2", "v"),
    ("قاعدة اليد اليمنى", "Right-Hand Rule", "", "", "U2C2", "v"),

    # ---------------- Unit 2 - Chapter 3 ----------------
    ("التحريض الكهرطيسي", "Electromagnetic Induction", "", "", "U2C3", "k"),
    ("تيار كهربائي متحرّض", "Induced Current", "i", "A", "U2C3", "k"),
    ("حقل مغناطيسي متحرّض", "Induced Magnetic Field", "B", "T", "U2C3", "k"),
    ("قوة محركة كهربائية متحرّضة", "Induced EMF", "ε", "V", "U2C3", "k"),
    ("تيارات فوكو", "Foucault (Eddy) Currents", "", "", "U2C3", "k"),
    ("التحريض الذاتي", "Self-Induction", "", "", "U2C3", "k"),
    ("ذاتية الوشيعة", "Self-Inductance of a Coil", "L", "H", "U2C3", "k"),
    ("طاقة كهرطيسية", "Electromagnetic Energy", "E_L", "J", "U2C3", "k"),
    ("مولّد", "Generator (Alternator)", "", "", "U2C3", "k"),
    ("محرّك", "Electric Motor", "", "", "U2C3", "k"),
    ("تيار متناوب جيبي", "Sinusoidal Alternating Current", "", "A", "U2C3", "k"),
    ("قانون فاراداي", "Faraday's Law", "", "", "U2C3", "v"),
    ("قانون لنز", "Lenz's Law", "", "", "U2C3", "v"),
    ("وشيعة", "Coil (Solenoid)", "", "", "U2C3", "v"),
    ("عدد اللفات", "Number of Turns", "N", "", "U2C3", "s"),
    ("مقياس الميكرو أمبير", "Microammeter", "", "", "U2C3", "v"),
    ("مقياس الميلي أمبير", "Milliammeter", "", "", "U2C3", "v"),
    ("القاطعة", "Switch (Key)", "K", "", "U2C3", "s"),
    ("دارة مغلقة", "Closed Circuit", "", "", "U2C3", "v"),
    ("الحقل الكهربائي المتحرّض", "Induced Electric Field", "E", "V/m", "U2C3", "v"),

    # ---------------- Unit 2 - Chapter 4 ----------------
    ("الدارات المهتزة والتيارات عالية التواتر", "Oscillating Circuits and High-Frequency Currents", "", "", "U2C4", "g"),
    ("الدارة المهتزة", "Oscillating Circuit", "", "", "U2C4", "k"),
    ("التفريغ المهتز", "Oscillatory Discharge", "", "", "U2C4", "k"),
    ("دور التفريغ", "Period of Discharge", "T₀", "s", "U2C4", "k"),
    ("التيارات العالية التواتر", "High-Frequency Currents", "", "", "U2C4", "k"),
    ("التيارات المنخفضة التواتر", "Low-Frequency Currents", "", "", "U2C4", "k"),
    ("المكثفة", "Capacitor", "C", "F", "U2C4", "s"),
    ("سعة المكثفة", "Capacitance", "C", "F", "U2C4", "s"),
    ("الطنين الكهربائي", "Electrical Resonance", "", "", "U2C4", "g"),
    ("التخامد", "Damping", "", "", "U2C4", "v"),
    ("الاهتزازات الكهربائية", "Electrical Oscillations", "", "", "U2C4", "v"),
    ("الإرسال", "Transmission (Radio)", "", "", "U2C4", "v"),

    # ---------------- Unit 2 - Chapter 5 ----------------
    ("التوتر اللحظي", "Instantaneous Voltage", "u", "V", "U2C5", "k"),
    ("التوتر الأعظمي", "Maximum (Peak) Voltage", "U_max", "V", "U2C5", "k"),
    ("التوتر المنتج", "Effective (RMS) Voltage", "U_eff", "V", "U2C5", "k"),
    ("الشدة اللحظية", "Instantaneous Current", "i", "A", "U2C5", "k"),
    ("الشدة العظمى", "Maximum (Peak) Current", "I_max", "A", "U2C5", "k"),
    ("الشدة المنتجة", "Effective (RMS) Current", "I_eff", "A", "U2C5", "k"),
    ("الاستطاعة المتوسطة المستهلكة", "Average Consumed Power", "P_avg", "W", "U2C5", "k"),
    ("فرق الكمون", "Potential Difference (Voltage)", "U", "V", "U2C5", "s"),
    ("المقاومة الصرفة", "Pure (Ohmic) Resistance", "R", "Ω", "U2C5", "v"),
    ("الممانعة", "Impedance", "Z", "Ω", "U2C5", "s"),
    ("ردية الوشيعة", "Inductive Reactance", "X_L", "Ω", "U2C5", "s"),
    ("ممانعة المكثفة (الاتساعية)", "Capacitive Reactance", "X_C", "Ω", "U2C5", "s"),
    ("المقاومة الأومية", "Ohmic Resistance", "r", "Ω", "U2C5", "s"),
    ("التحريضية (معامل التحريض الذاتي)", "Inductance", "L", "H", "U2C5", "v"),
    ("عامل الاستطاعة", "Power Factor", "cos φ", "", "U2C5", "v"),
    ("إنشاء فرينل", "Fresnel Construction (Phasor Diagram)", "", "", "U2C5", "v"),
    ("على وفاق بالطور", "In Phase", "", "", "U2C5", "v"),
    ("تقدم الطور / تأخر الطور", "Phase Lead / Phase Lag", "φ", "rad", "U2C5", "v"),
    ("دارة التفريغ", "Discharge Circuit", "", "", "U2C5", "v"),

    # ---------------- Unit 2 - Chapter 6 ----------------
    ("المحولة الكهربائية", "Electric Transformer", "", "", "U2C6", "g"),
    ("نسبة التحويل", "Transformation Ratio", "μ", "", "U2C6", "k"),
    ("مردود النقل", "Transmission Efficiency", "η", "", "U2C6", "k"),
    ("كفاءة المحولة", "Transformer Efficiency", "η", "", "U2C6", "k"),
    ("الدارة الثانوية", "Secondary Circuit", "", "", "U2C6", "v"),
    ("الدارة الأولية", "Primary Winding", "", "", "U2C6", "v"),
    ("الوشيعة الأولية", "Primary Coil", "N_p", "لفة", "U2C6", "k"),
    ("الوشيعة الثانوية", "Secondary Coil", "N_s", "لفة", "U2C6", "k"),
    ("خطوط النقل", "Transmission Lines", "", "", "U2C6", "v"),
    ("التيار المتواصل", "Direct Current (DC)", "", "A", "U2C6", "v"),
    ("التيار المتناوب", "Alternating Current (AC)", "", "A", "U2C6", "v"),

    # ---------------- Unit 3 - Chapter 1 ----------------
    ("الأمواج المستقرة", "Standing Waves", "", "", "U3C1", "g"),
    ("الأمواج المستقرة العرضية", "Transverse Standing Waves", "", "", "U3C1", "k"),
    ("بطن اهتزاز", "Antinode (Belly)", "", "", "U3C1", "k"),
    ("عقدة اهتزاز", "Node", "", "", "U3C1", "k"),
    ("نهاية مقيدة", "Fixed End", "", "", "U3C1", "k"),
    ("نهاية طليقة", "Free End", "", "", "U3C1", "k"),
    ("وتر مهتز", "Vibrating String", "", "", "U3C1", "k"),
    ("حبل مرن", "Elastic Cord", "", "", "U3C1", "k"),
    ("التجاوب", "Resonance", "", "", "U3C1", "k"),
    ("التواتر الأساسي", "Fundamental Frequency", "f₁", "Hz", "U3C1", "k"),
    ("المدروجات", "Harmonics", "", "Hz", "U3C1", "k"),
    ("الكتلة الخطية", "Linear Mass Density", "μ", "kg/m", "U3C1", "s"),
    ("سرعة الانتشار", "Propagation Speed", "v", "m/s", "U3C1", "s"),
    ("قوة الشد", "Tension Force", "F_T", "N", "U3C1", "s"),
    ("طول الموجة", "Wavelength", "λ", "m", "U3C1", "s"),
    ("الموجة", "Wave", "", "", "U3C1", "v"),
    ("اهتزاز عرضي", "Transverse Vibration", "", "", "U3C1", "v"),
    ("الرنانة", "Resonator", "", "", "U3C1", "v"),

    # ---------------- Unit 3 - Chapter 2 ----------------
    ("الأمواج المستقرة الطولية", "Longitudinal Standing Waves", "", "", "U3C2", "k"),
    ("انضغاط", "Compression", "", "", "U3C2", "k"),
    ("تخلخل", "Rarefaction", "", "", "U3C2", "k"),
    ("المزمار", "Pipe (Organ Pipe)", "", "", "U3C2", "k"),
    ("مزمار متشابه الطرفين", "Pipe with Two Identical Ends (Open-Open / Closed-Closed)", "", "", "U3C2", "k"),
    ("مزمار مختلف الطرفين", "Pipe with Two Different Ends (Open-Closed)", "", "", "U3C2", "k"),
    ("سرعة انتشار الصوت", "Speed of Sound", "v", "m/s", "U3C2", "s"),
    ("درجة الحرارة", "Temperature", "t / θ", "°C", "U3C2", "s"),
    ("عمود الهواء", "Air Column", "", "", "U3C2", "v"),
    ("الصوت الأساسي", "Fundamental Sound (First Harmonic)", "", "Hz", "U3C2", "v"),

    # ---------------- Unit 4 - Chapter 1 ----------------
    ("النماذج الذرية", "Atomic Models", "", "", "U4C1", "v"),
    ("الطيوف الذرية", "Atomic Spectra", "", "", "U4C1", "k"),
    ("التكميم", "Quantisation", "", "", "U4C1", "k"),
    ("طاقة التأين", "Ionisation Energy", "Ei", "J / eV", "U4C1", "k"),
    ("سويات الطاقة", "Energy Levels", "E", "J / eV", "U4C1", "k"),
    ("التحليل الطيفي", "Spectral Analysis", "", "", "U4C1", "k"),
    ("طيف مستمر", "Continuous Spectrum", "", "", "U4C1", "k"),
    ("طيف متقطع", "Discrete (Line) Spectrum", "", "", "U4C1", "k"),
    ("طيف انبعاث", "Emission Spectrum", "", "", "U4C1", "v"),
    ("طيف امتصاص", "Absorption Spectrum", "", "", "U4C1", "v"),
    ("الجسم الأسود", "Black Body", "", "", "U4C1", "v"),
    ("الذرة", "Atom", "", "", "U4C1", "v"),
    ("النواة", "Nucleus", "", "", "U4C1", "v"),
    ("المدار", "Orbit", "", "", "U4C1", "k"),
    ("الطبقة", "Shell (Electron Layer)", "", "", "U4C2", "k"),
    ("الحالة", "State (Level)", "", "", "U4C2", "k"),

    # ---------------- Unit 4 - Chapter 2 ----------------
    ("انتزاع الإلكترون", "Electron Extraction", "", "", "U4C2", "k"),
    ("تسريع الإلكترون", "Electron Acceleration", "", "", "U4C2", "k"),
    ("طاقة الارتباط", "Binding Energy", "E", "J / eV", "U4C2", "k"),
    ("مفعول الحت", "Sputtering Effect", "", "", "U4C2", "k"),
    ("المفعول الكهرضوئي", "Photovoltaic (Photoelectric) Effect", "", "", "U4C2", "k"),
    ("المفعول الكهرحراري", "Thermoelectric (Thermionic) Effect", "", "", "U4C2", "k"),
    ("الفعل الكهرحراري", "Thermionic Effect", "", "", "U4C4", "k"),
    ("القوة الكهربائية", "Electric Force", "F", "N", "U4C2", "k"),
    ("الاستطاعة الكهربائية", "Electric Power", "P", "W", "U4C2", "g"),
    ("المهبط", "Cathode", "", "", "U4C2", "v"),
    ("المصعد", "Anode", "", "", "U4C2", "v"),
    ("الإلكترون", "Electron", "e", "C", "U4C2", "s"),
    ("شحنة الإلكترون", "Electron Charge", "e", "C", "U4C2", "s"),
    ("كتلة الإلكترون", "Electron Mass", "m_e", "kg", "U4C2", "s"),
    ("الحزمة الإلكترونية", "Beam (Electron Beam)", "", "", "U4C2", "v"),
    ("المعادن", "Metals", "", "", "U4C2", "v"),

    # ---------------- Unit 4 - Chapter 3 ----------------
    ("الانفراغ الكهربائي", "Electric Discharge", "", "", "U4C3", "k"),
    ("أنبوب الانفراغ", "Discharge Tube", "", "", "U4C3", "k"),
    ("الأشعة المهبطية", "Cathode Rays", "", "", "U4C3", "k"),
    ("الشاشة المتألقة", "Fluorescent Screen", "", "", "U4C3", "g"),
    ("راسم الاهتزاز الإلكتروني", "Electronic Oscilloscope (CRO)", "", "", "U4C4", "k"),
    ("شبكة وهنلت", "Wehnelt Cylinder (Grid)", "", "", "U4C4", "k"),
    ("الجملة الحارفة", "Deflection System", "", "", "U4C4", "k"),
    ("التأين", "Ionisation", "", "", "U4C3", "v"),
    ("فرق الكمون الكافي", "Sufficient Potential Difference", "", "V", "U4C3", "v"),

    # ---------------- Unit 4 - Chapter 5 ----------------
    ("نظرية الكم", "Quantum Theory", "", "", "U4C5", "k"),
    ("نظرية أينشتاين", "Einstein's Theory", "", "", "U4C5", "k"),
    ("الفعل الكهرضوئي", "Photoelectric Effect", "", "", "U4C5", "k"),
    ("الخلية الكهرضوئية", "Photovoltaic Cell", "", "", "U4C5", "k"),
    ("الفوتون", "Photon", "", "", "U4C5", "v"),
    ("ثابت بلانك", "Planck's Constant", "h", "J·s", "U4C5", "s"),
    ("التواتر العتبة", "Threshold Frequency — مؤكَّد: الرمز f_s (ص238: f بحجم 12 + تابع s بحجم 8)", "f_s", "Hz", "U4C5", "v"),
    ("عمل الانتزاع", "Work Function", "W_s", "J", "U4C5", "v"),

    # ---------------- Unit 4 - Chapter 6 ----------------
    ("الأشعة السينية", "X-Rays", "", "", "U4C6", "k"),
    ("طبيعة الأشعة السينية", "Nature of X-Rays", "", "", "U4C6", "k"),
    ("امتصاص الأشعة السينية", "X-Ray Absorption", "", "", "U4C6", "k"),
    ("نفاذ الأشعة السينية", "X-Ray Penetration", "", "", "U4C6", "k"),
    ("التصوير الشعاعي", "Radiography", "", "", "U4C6", "v"),
    ("أنبوب توليد الأشعة السينية", "X-Ray Tube", "", "", "U4C6", "v"),
    ("هدف من معدن ثقيل", "Heavy Metal Target", "", "", "U4C6", "v"),

    # ---------------- Unit 4 - Chapter 7 ----------------
    ("أشعة الليزر", "Laser Radiation", "", "", "U4C7", "k"),
    ("الليزر", "Laser", "", "", "U4C7", "k"),
    ("الإصدار المحثوث", "Stimulated Emission", "", "", "U4C7", "k"),
    ("الإصدار التلقائي", "Spontaneous Emission", "", "", "U4C7", "k"),
    ("الوسط الفعال", "Active Medium", "", "", "U4C7", "k"),
    ("تضخيم الضوء", "Light Amplification", "", "", "U4C7", "v"),
    ("التجويف الرنان", "Resonant Cavity", "", "", "U4C7", "v"),

    # ---------------- Unit 5 - Chapter 1 ----------------
    ("الفيزياء الفلكية", "Astrophysics", "", "", "U5C1", "k"),
    ("جرم سماوي", "Astronomical Object", "", "", "U5C1", "k"),
    ("الكوكب", "Planet", "", "", "U5C1", "k"),
    ("النجم", "Star", "", "", "U5C1", "k"),
    ("المجرة", "Galaxy", "", "", "U5C1", "k"),
    ("طيوف النجوم", "Spectra of Stars", "", "", "U5C1", "k"),
    ("الانزياح الموجي", "Wave Displacement (Redshift)", "", "", "U5C1", "k"),
    ("تمدد الكون", "Expansion of the Universe", "", "", "U5C1", "k"),
    ("سرعة الإفلات", "Escape Velocity", "v", "m/s", "U5C1", "k"),
    ("نصف قطر شفارتزشيلد", "Schwarzschild Radius", "Rs", "m", "U5C1", "k"),
    ("الثقب الأسود", "Black Hole", "", "", "U5C1", "v"),
    ("القبة السماوية", "Celestial Sphere", "", "", "U5C1", "v"),
    ("إشعاع هوكنغ", "Hawking Radiation", "", "", "U5C1", "v"),
    ("ثابت الجذب العام", "Gravitational Constant", "G", "N·m²/kg²", "U5C1", "s"),
    ("الكتلة الشمسية", "Solar Mass", "", "kg", "U5C1", "v"),

    # ---------------- Section 0: symbols, constants, units ----------------
    ("الكتلة", "Mass", "m", "kg", "SYM", "s"),
    ("الزمن", "Time", "t", "s", "SYM", "s"),
    ("المسافة", "Distance", "d / x", "m", "SYM", "s"),
    ("الطول", "Length", "L / ℓ", "m", "SYM", "s"),
    ("نصف القطر", "Radius", "r / R", "m", "SYM", "s"),
    ("المساحة", "Area", "S / A", "m²", "SYM", "s"),
    ("الحجم", "Volume", "V", "m³", "SYM", "s"),
    ("الزاوية", "Angle", "θ / α", "rad", "SYM", "s"),
    ("السرعة", "Speed / Velocity", "v", "m/s", "SYM", "s"),
    ("التسارع الزاوي", "Angular Acceleration", "α", "rad/s²", "SYM", "s"),
    ("السرعة الزاوية الثابتة", "Constant Angular Velocity", "ω", "rad/s", "SYM", "s"),
    ("النبض", "Angular Frequency (Pulsation)", "ω", "rad·s⁻¹", "SYM", "s"),
    ("العمل", "Work", "W", "J", "SYM", "s"),
    ("الاستطاعة", "Power", "P", "W", "SYM", "s"),
    ("المردود", "Efficiency", "η", "%", "SYM", "s"),
    ("المقاومة الكهربائية", "Electrical Resistance", "R", "Ω", "SYM", "s"),
    ("الناقلية", "Conductance", "G", "S", "SYM", "s"),
    ("الحقل الكهربائي", "Electric Field", "E", "V/m", "SYM", "s"),
    ("الشحنة الكهربائية", "Electric Charge", "q", "C", "SYM", "s"),
    ("الكمون الكهربائي", "Electric Potential", "V", "V", "SYM", "s"),
    ("تسارع الجاذبية الأرضية", "Gravitational Acceleration", "g", "m/s² (تُعتمد 10)", "SYM", "s"),
    ("النفاذية المغناطيسية للخلاء", "Permeability of Free Space", "μ₀", "T·m/A (= 4π×10⁻⁷)", "SYM", "s"),
    ("المتر", "Metre", "m", "وحدة أساسية", "SYM", "s"),
    ("الكيلوغرام", "Kilogram", "kg", "وحدة أساسية", "SYM", "s"),
    ("الثانية", "Second", "s", "وحدة أساسية", "SYM", "s"),
    ("الأمبير", "Ampere", "A", "وحدة أساسية", "SYM", "s"),
    ("الفولط", "Volt", "V", "وحدة مشتقة", "SYM", "s"),
    ("الأوم", "Ohm", "Ω", "وحدة مشتقة", "SYM", "s"),
    ("الفاراد", "Farad", "F", "وحدة مشتقة", "SYM", "s"),
    ("الهنري", "Henry", "H", "وحدة مشتقة", "SYM", "s"),
    ("الويبر", "Weber", "Wb", "Wb", "SYM", "s"),
    ("التسلا", "Tesla", "T", "وحدة مشتقة", "SYM", "s"),
    ("الهرتز", "Hertz", "Hz", "وحدة مشتقة", "SYM", "s"),
    ("النيوتن", "Newton", "N", "وحدة مشتقة", "SYM", "s"),
    ("الجول", "Joule", "J", "وحدة مشتقة", "SYM", "s"),
    ("الواط", "Watt", "W", "وحدة مشتقة", "SYM", "s"),
    ("الكولون", "Coulomb", "C", "وحدة مشتقة", "SYM", "s"),
    ("الراديان", "Radian", "rad", "وحدة مشتقة", "SYM", "s"),
    ("الدرجة المئوية", "Degree Celsius", "°C", "وحدة مشتقة", "SYM", "s"),
    ("السنتيمتر", "Centimetre", "cm", "10⁻² m", "SYM", "s"),
    ("الغرام", "Gram", "g", "10⁻³ kg", "SYM", "s"),
    ("الإلكترون فولط", "Electronvolt", "eV", "1.6×10⁻¹⁹ J", "SYM", "s"),

    # ---------------- Section 6: general & laboratory vocabulary ----------------
    ("التجربة", "Experiment", "", "", "GEN", "v"),
    ("نشاط", "Activity", "", "", "GEN", "v"),
    ("خطوات التجربة", "Experimental Steps", "", "", "GEN", "v"),
    ("المواد اللازمة", "Required Materials", "", "", "GEN", "v"),
    ("النتائج", "Results", "", "", "GEN", "v"),
    ("أستنتج", "I Conclude", "", "", "GEN", "v"),
    ("ألاحظ", "I Observe", "", "", "GEN", "v"),
    ("أستنتاج", "Conclusion", "", "", "GEN", "v"),
    ("مسألة", "Problem (Exercise)", "", "", "GEN", "v"),
    ("المطلوب", "Required (to find)", "", "", "GEN", "v"),
    ("مستوى شاقولي", "Vertical Plane", "", "", "GEN", "v"),
    ("مستوى أفقي", "Horizontal Plane", "", "", "GEN", "v"),
    ("محور الدوران", "Axis of Rotation — يرمز له الكتاب بـ Δ (مثل Γ_η/Δ، Γ_w/Δ، Γ_R/Δ)", "Δ", "", "GEN", "v"),
    ("مجموع العزوم", "Sum of Moments — العلاقة الأساسية في التحريك الدوراني عند الأستاذ: ΣΓ = I_Δ·α", "ΣΓ", "m·N", "GEN", "v"),
    ("عزم مزدوجة الوزن", "Moment of the Weight Couple — منظومة الأستاذ", "Γ_ω", "m·N", "U1C3", "v"),
    ("عزم مزدوجة التوتر", "Moment of the Tension Couple", "Γ_T", "m·N", "U1C3", "v"),
    ("عزم مزدوجة ردّ الفعل", "Moment of the Reaction Couple", "Γ_R", "m·N", "U1C3", "v"),
    ("عزم مزدوجة القوة", "Moment of a Force Couple", "Γ_F", "m·N", "GEN", "v"),
    ("طول موجة العتبة", "Threshold Wavelength", "λ_s", "m", "U4C5", "v"),
    ("طاقة العتبة", "Threshold Energy (= عمل الانتزاع)", "E_s", "J", "U4C5", "v"),    ("حركة مستقيمة منتظمة", "Uniform Rectilinear Motion", "", "", "GEN", "v"),
    ("حركة اهتزازية", "Oscillatory Motion", "", "", "GEN", "v"),
    ("حركة دورانية", "Rotational Motion", "", "", "GEN", "v"),
    ("جملة", "System", "", "", "GEN", "v"),
    ("جملة مهتزة", "Oscillating System", "", "", "GEN", "v"),
    ("موضع التوازن", "Equilibrium Position", "", "", "GEN", "v"),
    ("وضع التوازن", "Equilibrium Position", "", "", "GEN", "v"),
    ("حالة التوازن", "State of Equilibrium", "", "", "GEN", "v"),
    ("محصلة القوى", "Resultant of Forces", "ΣF", "N", "GEN", "v"),
    ("القوى المؤثرة", "Acting Forces", "", "", "GEN", "v"),
    ("القوى الخارجية", "External Forces", "", "", "GEN", "v"),
    ("مهمل الكتلة", "Massless (Negligible Mass)", "", "", "GEN", "v"),
    ("عديم الفتل", "Torsion-Free", "", "", "GEN", "v"),
    ("متجانس", "Homogeneous / Uniform", "", "", "GEN", "v"),
    ("متناظر", "Symmetrical", "", "", "GEN", "v"),
    ("يتناسب طرداً مع", "Directly Proportional", "~", "", "GEN", "v"),
    ("يتناسب عكساً مع", "Inversely Proportional", "", "", "GEN", "v"),
    ("القيمة المطلقة", "Absolute Value", "| |", "", "GEN", "v"),
    ("القيمة الجبرية", "Algebraic Value", "", "", "GEN", "v"),
    ("القيمة العظمى", "Maximum Value", "", "", "GEN", "v"),
    ("القيمة الصغرى", "Minimum Value", "", "", "GEN", "v"),
    ("التغيّر", "Change / Variation", "Δ", "", "GEN", "v"),
    ("معدوم", "Zero (Nil)", "", "", "GEN", "v"),
    ("ينعدم", "Vanishes / Becomes Zero", "", "", "GEN", "v"),
    ("ثابت", "Constant", "", "", "GEN", "v"),
    ("متغيّر", "Variable", "", "", "GEN", "v"),
    ("العلاقة", "Relation / Equation", "", "", "GEN", "v"),
    ("عبارة", "Expression / Formula", "", "", "GEN", "v"),
    ("بدلالة", "In Terms Of", "", "", "GEN", "v"),
    ("نعوّض", "We Substitute", "", "", "GEN", "v"),
    ("الجذر التربيعي", "Square Root", "√", "", "GEN", "v"),
    ("الجيب (جيا)", "Sine", "sin", "", "GEN", "v"),
    ("جيب التمام", "Cosine", "cos", "", "GEN", "v"),
    ("اللوغاريتم", "Logarithm", "log", "", "GEN", "v"),
    ("الأس", "Exponent / Power", "", "", "GEN", "v"),
    ("الأساس", "Base", "", "", "GEN", "v"),
    ("الرسم البياني", "Graph", "", "", "GEN", "v"),
    ("المحور الأفقي", "Horizontal Axis", "", "", "GEN", "v"),
    ("المحور الشاقولي", "Vertical Axis", "", "", "GEN", "v"),
    ("الشكل المجاور", "Adjacent Figure", "", "", "GEN", "v"),
    ("الشكل", "Figure / Diagram", "", "", "GEN", "v"),
    ("أسلاك توصيل", "Connecting Wires", "", "", "GEN", "v"),
    ("على التسلسل", "In Series", "", "", "GEN", "v"),
    ("على التفرّع", "In Parallel", "", "", "GEN", "v"),
    ("مصباح كهربائي", "Electric Lamp", "", "", "GEN", "v"),
    ("مولد التيار المتواصل", "DC Generator", "", "", "GEN", "v"),
    ("مولد التيار المتناوب", "AC Generator", "", "", "GEN", "v"),
    ("إبرة مغناطيسية", "Magnetic Needle", "", "", "GEN", "v"),
    ("حقل مغناطيسي منتظم", "Uniform Field", "", "", "GEN", "v"),
    ("منطقة يسودها حقل", "Field Region", "", "", "GEN", "v"),
    ("سرعة ابتدائية", "Initial Velocity", "v₀", "m/s", "GEN", "v"),
    ("لحظة", "Instant", "", "", "GEN", "v"),
    ("مدة", "Duration", "Δt", "s", "GEN", "v"),
    ("اتجاه", "Direction", "", "", "GEN", "v"),
    ("منحى", "Orientation / Direction", "", "", "GEN", "v"),
    ("يعامد", "Is Perpendicular To", "⊥", "", "GEN", "v"),
    ("يوازي", "Is Parallel To", "∥", "", "GEN", "v"),
    ("يعاكس", "Opposes", "", "", "GEN", "v"),
    ("يتفق بالطور", "In Phase", "", "", "GEN", "v"),
    ("تفكير ناقد", "Critical Thinking", "", "", "GEN", "v"),
    ("اختبر نفسك", "Test Yourself", "", "", "GEN", "v"),
    ("مشروع", "Project", "", "", "GEN", "v"),
    ("أهداف", "Objectives", "", "", "GEN", "v"),
    ("الكلمات المفتاحية", "Key Words", "", "", "GEN", "v"),
    ("المصطلحات الإنكليزية", "English Terminology", "", "", "GEN", "v"),

    # ---------------- Section 7-a: allowed synonyms (never in questions) ----------------
    ("الفيزياء الطبية", "Medical Physics — NOT in this book", "", "", "BAN", "v"),
    ("المفاعلة", "Reactance (Egyptian) — Syrian: ردية الوشيعة X_L / الممانعة Z", "", "", "BAN", "v"),
    ("المفاعلة الحثية", "Inductive Reactance (Egyptian) — Syrian: ردية الوشيعة", "", "", "BAN", "v"),
    ("المفاعلة السعوية", "Capacitive Reactance (Egyptian) — Syrian: الاتساعية X_C", "", "", "BAN", "v"),
    ("المعاقة", "Impedance (foreign) — Syrian: الممانعة Z", "", "", "BAN", "v"),
    ("الشدة الفعالة", "RMS Current (Egyptian) — Syrian: الشدة المنتجة I_eff", "", "", "BAN", "v"),
    ("التوتر الفعال", "RMS Voltage (Egyptian) — Syrian: التوتر المنتج U_eff", "", "", "BAN", "v"),
    ("معامل القدرة", "Power Factor (Egyptian) — Syrian: عامل استطاعة الدارة", "", "", "BAN", "v"),
    ("الكهرومغناطيسية", "Electromagnetic (foreign form) — Syrian: الكهرطيسية", "", "", "BAN", "v"),
    ("الغاز المخلخل", "Rarefied Gas (Egyptian) — absent from the Syrian book & exams", "", "", "BAN", "v"),
    ("الزمن المضاعف", "Dilated Time (Egyptian) — Syrian book says: تمدد الزمن", "", "", "BAN", "v"),
    ("التردد", "Frequency — المرجوح؛ المصطلح الرسمي: التواتر (أُجيز استعماله)", "", "", "SYN", "v"),
    ("الجهد", "Voltage — المرجوح؛ المصطلح الرسمي: التوتر / فرق الكمون (أُجيز استعماله)", "", "", "SYN", "v"),
    ("شبه موصل", "Semiconductor — not in this book (use الجسم الصلب)", "", "", "BAN", "v"),
    ("نصف ناقل", "Semiconductor — not in this book", "", "", "BAN", "v"),
    ("الترانزستور", "Transistor — not in this book", "", "", "BAN", "v"),
    ("المقحل", "Transistor (Syrian term) — not in this book", "", "", "BAN", "v"),
    ("المحاثة", "Inductance (Egyptian) — book says ذاتية الوشيعة", "", "", "BAN", "v"),
    ("الابتدائية (بمعنى ملفّ المحوّلة)", "‘Primary’ as a transformer winding — WRONG here: in this book الابتدائية means ‘initial’ (الطور الابتدائي / السرعة الابتدائية). The book's transformer term is الأولية / الوشيعة الأولية.", "", "", "BAN", "v"),
    ("معامل التحريض الذاتي", "Self-Inductance (Egyptian) — book says ذاتية الوشيعة", "", "", "BAN", "v"),
    ("الفيض المغناطيسي", "Magnetic Flux (Egyptian) — book says التدفق المغناطيسي", "", "", "BAN", "v"),
    ("الذبذبة", "Oscillation (Egyptian) — book says اهتزاز", "", "", "BAN", "v"),
    ("التيار المستمر", "DC (Egyptian) — book says التيار المتواصل", "", "", "BAN", "v"),
    ("المجال", "Field (Egyptian) — book says الحقل", "", "", "BAN", "v"),
    ("الزنبرك", "Spring (Egyptian) — book says نابض", "", "", "BAN", "v"),
    ("السرعة المتجهة", "Velocity vector — book says شعاع السرعة", "", "", "BAN", "v"),
    ("شعاع السرعة", "Velocity Vector", "v⃗", "m/s", "GEN", "v"),
    ("العطالة", "Inertia", "", "", "GEN", "v"),
    ("النوسة", "(One) Oscillation / Swing", "", "", "GEN", "v"),
    ("مستوي النوسان", "Plane of Oscillation", "", "", "GEN", "v"),
    ("الهزازة", "Vibrator / Oscillator", "", "", "GEN", "v"),
    ("عزم القصور", "Moment of Inertia (Egyptian) — book says عزم العطالة", "", "", "BAN", "v"),
    ("الموجة الموقوفة", "Standing Wave (Egyptian) — book says الموجة المستقرة", "", "", "BAN", "v"),
    ("أشعة إكس", "X-Rays (loan translation) — book says الأشعة السينية", "", "", "BAN", "v"),
    ("القصور الذاتي", "Inertia — قرار الأستاذ: العطالة فقط", "", "", "BAN", "v"),
    ("الكثافة", "Density — قرار الأستاذ: الصواب الكتلة الحجمية", "", "", "BAN", "v"),
    ("التأثير الكهروضوئي", "Photoelectric Effect (Egyptian) — book says الفعل الكهرضوئي", "", "", "BAN", "v"),
]
